### ISSUE TITLE
un-usable

### ISSUE THREAD

**Issue by justintime4tea** [kobotoolbox/dist-kobo-devel#32] opened 2015-08-10 21:16 UTC
- Original content removed by author because he felt bad and wasn't very constructive.

- Please make this actually usable for the community please.

**Comment by tinok** [comment] 2015-08-11 06:42
Which steps did you follow that didn't work for you? Both the instructions
from the pre built box and building it from scratch work for us and for
many others.

We appreciate if you want to help make it easier to install (including NY
improving the instructions) , so if you want to contribute please point out
specific issues that can be addressed individually.

**Comment by esmail** [comment] 2015-08-11 18:10
Unless there's been a mixup on my end, I've been running the latest pre-built box and it's working fine for me with Enketo Express. I'm not able to test it with Collect currently though, since I don't have an Android device handy. @justintime4tea if you're building from scratch, you might want to populate the file `env/env.sh` with the following:
```
export KOBOCAT_BRANCH=vagrant_stable
export KOBOCAT_TEMPLATES_BRANCH=vagrant_stable
export KOBOFORM_BRANCH=vagrant_stable
```
. I'll put in a PR to create a shortcut for this behaviour.

**Comment by tinok** [comment] 2015-08-11 18:36
Closing this issue. Please create specific bugs with exact steps on how to reproduce them, or contact support@kobotoolbox.org or kobo-dev@googlegroups.com with questions on particular issues.

**Closed by tinok** 2015-08-11 18:36 UTC
